# Dont worry about this file.. Just to remind me how that small one was created.

default:
	echo 'Check no-one edited it manually'

bitvote_logo_small.png:
	convert -trim -resize 120 bitvote_logo.png bitvote_logo_small.png

bitvote_logo_smaller.png:
	convert -trim -resize 80 bitvote_logo.png bitvote_logo_smaller.png
